### PR TITLE
FOLIO-2427 automated module version handling ModuleDescriptor

### PR DESCRIPTION
**Pull request by dcrossleyau**
Added automated module version handling to ModuleDescriptor and POM:
https://dev.folio.org/guides/commence-a-module/#back-end-descriptors

I know that this maven build is broken until the "ncip" dependencies are available. Anyway, i cannot build it to test my changes, so please you do. After that, there should be transformed descriptors at target/*Descriptor.json

The files in this repository are not yet following the FOLIO [coding style](https://dev.folio.org/guidelines/contributing/#coding-style) conventions, so i hope that i did not mangle your files by copy-and-reindent from mod-notes.

You should investigate other ModuleDescriptors. For example the "requires/id" in other MDs does not use the "mod-" prefix.

### CODE REVIEW

**Comment by mis306lu** [comment]
Thanks for the updates.  I will test the changes & take a look at the conventions.  Question - when you say: "You should investigate other ModuleDescriptors. For example the "requires/id" in other MDs does not use the "mod-" prefix."  The MD for NCIP does not use the 'mod-' prefix in the requires section.  I'm not sure what you are suggesting I change.  Would you mind clarifying? thank you!

**Comment by dcrossleyau** [comment]
Sorry, a typo. I meant the "provides/id". See for example [mod-rtac](https://github.com/folio-org/mod-rtac/blob/master/descriptors/ModuleDescriptor-template.json) which just uses "rtac".

**Comment by mis306lu** [comment]
Got it!  Thanks!

**Comment by dcrossleyau** [comment]
I see that you removed the "-SNAPSHOT" from the "version" in the POM. Please note that this is a required part of the release procedures and the continuous integration: 
https://dev.folio.org/guidelines/release-procedures/

For example refer to the current mod-rtac. Its POM has "1.4.0-SNAPSHOT" being the master branch in development towards its next release, i.e. "1.4.0"

**Comment by mis306lu** [comment]
Corrected.  thank you!

**Pull request merged**
